
# alwayse use absolute paths

##### RESOURCES #####
mem: '32000'
threads: 2
partition: 'shortq'

##### GENERAL #####
annotation: /research/home/sreichl/projects/macroIC/config/AKsmall_mixscape_seurat_annotation.csv
result_path: /nobackup/lab_bock/projects/macroIC/results/AKsmall/
project_name: AKsmall

##### MIXSCAPE #####

# used to split gRNA terms into target gene and guide number eg for symbol "-": STAT1-3 -> gene=STAT1; guide RNA number=3
grna_split_symbol: "-"

# which assay to use (eg "SCT" or "RNA"), if scale.data is empty standard Seurat methods are applied: NormalizeData(object = data) %>% FindVariableFeatures() %>% ScaleData()
assay: "SCT"

# perform analysis using only variable features (yes=1, no=0)
variable_features_only: 0

# parameters for https://satijalab.org/seurat/reference/calcperturbsig
CalcPerturbSig:
    grna_col: "gRNAcall"
    gene_col: "KOcall"
    nt_term: "NonTargeting"
    n_neighbors: 30
    ndims: 40
    split_by_col: ""

# parameters for https://satijalab.org/seurat/reference/runmixscape
RunMixscape:
    mixscape_fine_mode: 'FALSE' 
    lfc_th: 0.1
    split_by_col: 'condition'
    min_de_genes: 5
    min_cells: 5
    prtb_type: "KO"

##### LDA #####

# parameters for https://satijalab.org/seurat/reference/mixscapelda
MixscapeLDA:
    npcs: 10

##### VISUALIZATION #####

# names for the Seurat Assays mapped to 10X genomics feature Antibody_Capture (leave empty "" if not applicable)
Antibody_Capture: "AB"
